---
title: "Data Visualisation Portfolio"
output: html_notebook
---

This page showcases data visualisation created during my Grad Dip of Health Data Science studies at UNSW.

The first one is that of a DAGs (Direct Acyclic Graph) or commonly known as a causal diagram.

```{r include = FALSE, echo=FALSE}
library(GLMsData)
library(dplyr)
library(tidyverse)
library(dagitty)
# library(MatchIt)
library(cobalt)
# library(sjPlot)
library(ggdag)
# library(ggplot2)

#DAG diagram using dagify
node_details <- tribble(
  ~name, ~label, ~x, ~y,
  "comorbid", "Comorbidities", 1, 1,
  "wt", "Weight", 2.5, 1,
  "ht", "Height", 4, 1,
  "physact", "Physical Activity", 5.5, 1,
  "smoke", "Smoking", 1, 3,
  "lung_cap", "Lung Capacity", 5.5, 3,
  "ethnic", "Ethnicity", 1, 5,
  "age", "Age", 3.25, 5,
  "gender", "Gender", 5.5, 5,
  
)

node_labels <- node_details$label
names(node_labels) <- node_details$name

lungcap_dag<- ggdag::dagify(lung_cap ~ gender + age + ethnic + 
                          smoke + comorbid + wt + ht + physact,
                        smoke ~ gender + age + ethnic , 
                        comorbid ~ smoke,
                        wt ~ smoke,
                        ht ~ smoke,
                        physact ~ smoke,
                        exposure = "smoke",
                        outcome = "lung_cap",
                        coords = node_details,
                        labels = node_labels)

# Mapping DAG into a tidy data frame for plotting
lungcap_dag_tidy <- lungcap_dag %>% 
  tidy_dagitty() %>%
  node_status()   # Add column
  
status_colors <- c(exposure = "#0074D9", outcome = "#FF4136", latent = "#FF4136")

lungcapdag<-ggplot(lungcap_dag_tidy, aes(x = x, y = y, xend = xend, yend = yend)) +
                geom_dag_edges() +
                geom_dag_point(aes(color = status)) +
                geom_dag_label_repel(aes(label = label, fill = status), seed = 1234,
                        color = "white", fontface = "bold") +
                scale_color_manual(values = status_colors, na.value = "grey20") +
                scale_fill_manual(values = status_colors, na.value = "grey20") +
                guides(color = "none", fill = "none") + 
                theme_dag()
```

``` {r echo = FALSE, include = TRUE, fig.width = 4, fig.height = 4, fig.align = "center"}
lungcapdag
```
The code of the above diagram is shown below:

``` {r}

#DAG diagram using dagify
node_details <- tribble(
  ~name, ~label, ~x, ~y,
  "comorbid", "Comorbidities", 1, 1,
  "wt", "Weight", 2.5, 1,
  "ht", "Height", 4, 1,
  "physact", "Physical Activity", 5.5, 1,
  "smoke", "Smoking", 1, 3,
  "lung_cap", "Lung Capacity", 5.5, 3,
  "ethnic", "Ethnicity", 1, 5,
  "age", "Age", 3.25, 5,
  "gender", "Gender", 5.5, 5,
  
)

# Labels for nodes
node_labels <- node_details$label
names(node_labels) <- node_details$name

# Laying out the nodes and the causal arrows ie exposure to outcome
lungcap_dag<- ggdag::dagify(lung_cap ~ gender + age + ethnic + 
                          smoke + comorbid + wt + ht + physact,
                        smoke ~ gender + age + ethnic , 
                        comorbid ~ smoke,
                        wt ~ smoke,
                        ht ~ smoke,
                        physact ~ smoke,
                        exposure = "smoke",
                        outcome = "lung_cap",
                        coords = node_details,
                        labels = node_labels)

# Mapping DAG into a tidy data frame for plotting
lungcap_dag_tidy <- lungcap_dag %>% 
  tidy_dagitty() %>%
  node_status()   # Add column
  
status_colors <- c(exposure = "#0074D9", outcome = "#FF4136", latent = "#FF4136")

lungcapdag<-ggplot(lungcap_dag_tidy, aes(x = x, y = y, xend = xend, yend = yend)) +
                geom_dag_edges() +
                geom_dag_point(aes(color = status)) +
                geom_dag_label_repel(aes(label = label, fill = status), seed = 1234,
                        color = "white", fontface = "bold") +
                scale_color_manual(values = status_colors, na.value = "grey20") +
                scale_fill_manual(values = status_colors, na.value = "grey20") +
                guides(color = "none", fill = "none") + 
                theme_dag()
```

